language: ruby
cache: bundler
rvm:
  - 2.1.3
bundler_args: -j4 --without development production --quiet
script:
  - RAILS_ENV=test bundle exec rake db:setup
  - bundle exec rake spec
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database spree_market_test;' -U postgres
